/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BmrCalculator: (typeof import('./../src/components/BmrCalculator/src/BmrCalculator.vue'))['default']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElDrawer: (typeof import('element-plus/es'))['ElDrawer']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    Footer: (typeof import('./../src/components/Footer/src/Footer.vue'))['default']
    Header: (typeof import('./../src/components/Header/src/Header.vue'))['default']
    LocaleDropdown: (typeof import('./../src/components/LocaleDropdown/src/LocaleDropdown.vue'))['default']
    Logo: (typeof import('./../src/components/Logo/src/Logo.vue'))['default']
    MealPlanHeader: (typeof import('./../src/components/MealPlanHeader/src/MealPlanHeader.vue'))['default']
    NavDesktop: (typeof import('./../src/components/Header/src/NavDesktop.vue'))['default']
    NavMobile: (typeof import('./../src/components/Header/src/NavMobile.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Sidebar: (typeof import('./../src/components/Sidebar/src/Sidebar.vue'))['default']
    StepError: (typeof import('./../src/components/StepError/src/StepError.vue'))['default']
    ThemeSwitch: (typeof import('./../src/components/ThemeSwitch/src/ThemeSwitch.vue'))['default']
  }
}
